const globalConstant = {
  ERROR_INFO: "Something Went wrong!",
  ERROR_MESSAGE: "Error message",
  BACK: "Back",
  SIMULATE_ERROR: "Simulate Error",
  SIMULATE_ASYNC_ERROR: "Simulate Async Error",
  TEXT: "text",
  INFO_COLOR: "info",
  ASYNC_ERROR_MESSAGE: "Async error raised",
  OUTLINED: "outlined",
  PRIMARY_COLOR: "primary",
  SYNC_ERROR: "Sync error",
  CENTER: "center",
  GAP: 2,
  DEVELOPMENT_MODE: "development",
  LOGIN: "auth",
  CONTAINED: "contained",
  LOGOUT: "logout",
  TENANT_ID: "Dinesh21",
  TOKEN: "2d1i8n",
  ENTER_LOGIN: "enter login",
  WELCOME: "Welcome",
  PASSWORD: "your password is",
  LOGGEDOUT: "You are logged out",
  COMPONENT: "Component",
  ADD_USER: "Add User",
  SUCCESS_MESSAGE: "This is a success message!",
  ERROR_MESSAGE_IN: "This is a error message!",
  SUCCESS: "success",
  ERROR: "error",
  HTTP_UNAUTHORIZED_ERROR_STATUS_CODE: 401,
  HTTP_INTERNAL_SERVER_ERROR_STATUS_CODE: 501,
  AI_TRACKER_ID_UNAUTHORISED_ACCESS_ERROR: "API_ERROR_401",
  AI_TRACKER_ID_INTERNAL_SERVER_ERROR: "API_ERROR_500",
  AI_TRACKER_ID_LOGIN_UNAUTHORISED_ACCESS_ERROR: "LOGIN_ERROR_401",
  AI_TRACKER_ID_LOGIN_INTERNAL_SERVER_ERROR: "LOGIN_ERROR_500",
  HTTP_SUCCESS_STATUS_TEXT: "success",
  COMPANY_NAME_TEXT: "mcParts",
  TOGGLE_EVENT_PASSWORD_VISIBILITY_TEXT: "toggle password visibility",
  TEXT_FIELD_VARIANT: "outlined",
  AUTO_COMPLETE_OFF: "off",
  PLACEHOLDER_DEFAULT: "",
  CLASS_NAME: "my-2",
  PASSWORD_TYPE: "password",
  TEXT_TYPE: "text",
  HTTP_SUCCESS_STATUS_CODE: 200,
  FORGOT_PASSWORD_SLICE: "forgotPassword",
  HTTP_INVALID_USER_CODE: 403,
  INVALID_USER_MESSAGE: "Invalid User",
  AZURE_TRACK_FORGOT_PASSWORD_ERR: "ForgotPasswordError",
  AZURE_TRACK_FORGOT_PASSWORD_INVALID_USER: "ForgotPasswordInvalidUser",
  AZURE_TRACK_FORGOT_PASSWORD_SUCCESS: "ForgotPasswordSuccess",
  AI_LOGIN_IDENTIFIER: "LOGIN_EVENT",
  AI_RESET_PASSWORD_INDENTIFIER: "RESET_PASSWORD_EVENT",
  AI_GET_USER_DATA_IDENTIFIER: "GET_USERDATA",
  SIDEBAR_CONTEXT_ERROR: "useSidebar must be used within a SidebarProvider",
  MCPARTS_LOGO_ALT_TEXT: "mcparts-logo",
  PORTAL_NAME_TEXT: "mcParts",
  PROFILE_KEYWORD: "Profile",
  SAVE_TEXT: "Save",
  SUBMIT_TEXT: "Submit",
  CANCEL_TEXT: "Cancel",
  UNAUTHORIZED_ACCESS: "UnAuthorised Access",
  QUERY_PARAM_ID: "id",
  QUERY_PARAM_TOKEN: "token",
  CANCEL_CONFIRM_TITLE: "Are you sure you want to cancel?",
  CANCEL_CONFIRM_DESC:
    "Please note that you will not be able to recover these later.",
};

export default globalConstant;
